JsonRefError: add __str__ helper
When JsonRefError is raised today, the default error message is not helpful:
  File ".../jsonref.py", line 221, in _error
    cause=cause
jsonref.JsonRefError

Let's include the message in the __str__ helper so we get:
  File ".../jsonref.py", line 221, in _error
    cause=cause
jsonref.JsonRefError: ValueError: unknown url type: defs.json